services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: archlens-rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: archlens
      RABBITMQ_DEFAULT_PASS: archlens

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: