name: ArchLens CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Nodde.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

#      - name: Run tests
#       run: npm test

      - name: Buid application
        run: npm run build
      
      - name: Configure Aws Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::161958365524:role/GitHubActionsArchLensRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t archlens:latest .

      - name: Tag Docker image
        run: |
          docker tag archlens:latest \
            161958365524:dkr.ecr.us-east-1.amazonaws.com/archlens:latest

      - name: Push Docker image
        run: |
          docker push \
            161958365524.dkr.ecr.us-east-1.amazonaws.com/archlens:latest
