name: ArchLens Rollback

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: "ID do deploy para fazer rollback"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get deployment SHA
        id: deployment
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          SHA=$(gh run view ${{ inputs.run_id }} \
            --json headSha \
            --jq '.headSha')

          echo "Selected SHA: $SHA"
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: List successful deployments
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh run list \
            --workflow deploy.yml \
            --status success \
            --limit 10 \
            --json databaseId,createdAt,headSha,displayTitle \
            --jq '.[] | {
              id: .databaseId,
              date: .createdAt,
              sha: .headSha,
              commit: .displayTitle
            }'